name: isankaskao
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  animate_gradient: ^0.0.3
  animated_text_kit: ^4.2.2
  battery_plus: ^6.0.1
  confetti: ^0.7.0
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  http: ^1.2.1
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
